package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"

	graphql_api "github.com/DmitryLogunov/trading-platform/core/graphql-api"
)

// GetPosts is the resolver for the getPosts field.
func (r *queryResolver) GetPosts(ctx context.Context) ([]*graphql_api.Post, error) {
	var posts []*graphql_api.Post

	GetPosts := r.Database.Model(&posts).Find(&posts)

	if GetPosts.Error != nil {
		fmt.Println(GetPosts.Error)
		return nil, GetPosts.Error
	}
	return posts, nil
}

// GetUsers is the resolver for the getUsers field.
func (r *queryResolver) GetUsers(ctx context.Context) ([]*graphql_api.User, error) {
	panic(fmt.Errorf("not implemented: GetUsers - getUsers"))
}

// Query returns graphql_api.QueryResolver implementation.
func (r *Resolver) Query() graphql_api.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
