package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"

	graphqlApi "github.com/DmitryLogunov/trading-platform/internal/app/graphql-api"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input graphqlApi.NewPost) (*graphqlApi.Post, error) {
	return r.GqlServices.PostsService.CreatePost(ctx, r.MongoDB, input)
}

// StartJob is the resolver for the startJob field.
func (r *mutationResolver) StartJob(ctx context.Context, input graphqlApi.JobData) (string, error) {
	return r.GqlServices.JobsService.StartJob(r.Scheduler, input)
}

// StopJob is the resolver for the stopJob field.
func (r *mutationResolver) StopJob(ctx context.Context, tag string) (string, error) {
	return r.GqlServices.JobsService.StopJob(r.Scheduler, tag)
}

// Mutation returns graphqlApi.MutationResolver implementation.
func (r *Resolver) Mutation() graphqlApi.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
