version: '3.8'

services:
  mongodb:
    image: mongo:4.4.22
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb:/data/db
      - mongodb-config:/data/configdb

  trading-platform-graphql-api:
    image: trading-platform-graphql-api
    depends_on:
      - mongodb
    ports:
      - 0.0.0.0:${HTTP_GRAPHQL_EXPOSE_PORT}:${HTTP_GRAPHQL_PORT}
    environment:
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_PORT: ${MONGODB_PORT}
      HTTP_GRAPHQL_PORT: ${HTTP_GRAPHQL_PORT}
    volumes:
      - ../.env:/usr/src/app/.env:ro
    container_name: trading-platform-graphql-api
    command: ["/bin/sh", "-ce", "sleep 2 && ./trading-platform-graphql-api"]

  trading-platform-rest-api:
    image: trading-platform-rest-api
    depends_on:
      - mongodb
    ports:
      - 127.0.0.1:${HTTP_REST_EXPOSE_PORT}:${HTTP_REST_PORT}
    environment:
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_PORT: ${MONGODB_PORT}
      HTTP_GRAPHQL_PORT: ${HTTP_REST_PORT}
    volumes:
      - ../.env:/usr/src/app/.env:ro
    container_name: trading-platform-rest-api
    command: ["/bin/sh", "-ce", "sleep 2 && ./trading-platform-rest-api"]

volumes:
  mongodb:
  mongodb-config:

networks:
  trading-platform-backend-net:
    external: false
    driver: bridge
    name: trading-platform-backend-net