version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb:/data/db
      - mongodb-config:/data/configdb

volumes:
  mongodb:
  mongodb-config:

networks:
  trading-platform-backend-net:
    external: false
    driver: bridge
    name: trading-platform-backend-net