FROM golang:alpine AS builder

RUN mkdir -p /go/src/github.com/DmitryLogunov/trading-platform-backend
WORKDIR /go/src/github.com/DmitryLogunov/trading-platform-backend
COPY . /go/src/github.com/DmitryLogunov/trading-platform-backend

RUN apk --no-cache add git

RUN go build -o /go/src/github.com/DmitryLogunov/trading-platform-backend/trading-platform-graphql-api cmd/graphql-api/main.go

FROM alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY --from=builder /go/src/github.com/DmitryLogunov/trading-platform-backend/trading-platform-graphql-api .

CMD ["./trading-platform-graphql-api"]