version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=qwer1234
    volumes:
      - trading-platform-api-mongodb:/data/db
      - trading-platform-api-mongodb-config:/data/configdb

  trading-platform-api:
    image: trading-platform-api
    depends_on:
      - db
    ports:
      - 127.0.0.1:${HTTP_EXPOSE_PORT}:${HTTP_PORT}
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      HTTP_PORT: ${HTTP_PORT}
    container_name: trading-platform-api
    command: ["/bin/sh", "-ce", "sleep 2 && ./trading-platform-api"]

volumes:
  trading-platform-api-db-volume:
  trading-platform-api-mongodb:
  trading-platform-api-mongodb-config:

networks:
  golang-graphql-todolist-net:
    external: false
    driver: bridge
    name: golang-graphql-api-todolist-net