version: '3.8'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: mysql_user
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 0.0.0.0:${MYSQL_EXPOSE_PORT}:3306
    expose:
      - ${MYSQL_EXPOSE_PORT}
    volumes:
      - ./init-data:/init-data
      - db-volume:/var/lib/mysql

  graphql-api:
    image: golang-graphql-todolist
    depends_on:
      - db
    ports:
      - 127.0.0.1:${HTTP_PORT}:3000
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      HTTP_PORT: ${HTTP_PORT}
    container_name: graphql-api
    command: ["/bin/sh", "-ce", "sleep 2 && ./golang-graphql"]

volumes:
  db-volume:

networks:
  golang-graphql-todolist-net:
    external: false
    driver: bridge
    name: golang-graphql-todolist-net