#! /bin/bash
if [ ${1} == "" ] || [ ${1} == "graphql" ]; then
  go build  -o ./trading-platform-graphql-api cmd/graphql-api/main.go
fi

if [ ${1} == "" ] || [ ${1} == "rest" ]; then
  go build -o ./trading-platform-rest-api cmd/rest-api/main.go
fi