package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"fmt"

	graphql_api "github.com/DmitryLogunov/trading-platform/internal/api/graphql-api"
	mongodbModels "github.com/DmitryLogunov/trading-platform/internal/database/mongodb/models"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input graphql_api.NewPost) (*graphql_api.Post, error) {
	postsModel := mongodbModels.Post{
		Title:   input.Title,
		Content: input.Content,
		Author:  input.Author,
		Hero:    input.Hero,
	}

	addedPost, err := postsModel.CreatePost(ctx, &postsModel, r.MongoDB)

	if err != nil {
		fmt.Println(err)
		return nil, err
	}

	return &graphql_api.Post{
		ID:          addedPost.ID.Hex(),
		Title:       addedPost.Title,
		Content:     addedPost.Content,
		Author:      addedPost.Author,
		Hero:        addedPost.Hero,
		PublishedAt: addedPost.PublishedAt,
		UpdatedAt:   addedPost.UpdatedAt,
	}, nil
}

// Mutation returns graphql_api.MutationResolver implementation.
func (r *Resolver) Mutation() graphql_api.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
