// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql_api

import (
	"time"
)

type NewPost struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Author  string `json:"author"`
	Hero    string `json:"hero"`
}

type NewUser struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
}

type Post struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	Author      string    `json:"author"`
	Hero        string    `json:"hero"`
	PublishedAt time.Time `json:"publishedAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type User struct {
	ID        string    `json:"id"`
	FirstName string    `json:"firstName"`
	LastName  string    `json:"lastName"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
