name: deployment

on:
  push:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: pull, build & run
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd ${{ secrets.PROJECTPATH }}
            git checkout master 
            git pull https://${{ secrets.GITHUBPAT }}@github.com/DmitryLogunov/trading-platform-backend.git        
            .infra/scripts/deploy
