name: deployment

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: pull & build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd ${{ secrets.PROJECTPATH }}
            git checkout master 
            git pull
            docker build -f .infra/Dockerfile.graphql-api -t trading-platform-graphql-api .
            docker build -f .infra/Dockerfile.rest-api -t trading-platform-rest-api .
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            cd /home/projects/infra
            export $(cat /home/projects/infra/env-files/trading-platform-backend/master/.env) && docker-compose restart
